# Python CircleCI 2.0 configuration file

version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: python tests
          command: |
            . venv/bin/activate
            pytest
workflows:
  version: 2
  tests:
    jobs:
      - backend_tests
